extractClassFieldsToCsv BaseAlignedWindowAssigner.fields.txt
extractClassFieldsToCsv EventTimeSessionWindows.fields.txt
extractClassFieldsToCsv ProcessingTimeSessionWindows.fields.txt
extractClassFieldsToCsv SlidingAlignedProcessingTimeWindows.fields.txt
extractClassFieldsToCsv SlidingEventTimeWindows.fields.txt
extractClassFieldsToCsv SlidingProcessingTimeWindows.fields.txt
extractClassFieldsToCsv TumblingEventTimeWindows.fields.txt
extractClassFieldsToCsv TumblingProcessingTimeWindows.fields.txt
