extractClassFieldsToCsv EvictingWindowOperator.fields.txt
extractClassFieldsToCsv KeyMap.fields.txt
extractClassFieldsToCsv MergingWindowSet.fields.txt
extractClassFieldsToCsv TimestampedValue.fields.txt
extractClassFieldsToCsv WindowOperator.fields.txt
