- name: exercise in chapter7 complex playbooks
  hosts: vagrant2
  sudo: True
  gather_facts: False
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost
  tasks:
    - name: Run myprog
      sudo: false
      command: /opt/myprog
      register: result
      ignore_errors: True

    - debug: var=result

    - debug: msg="Stop running the playbook if myprog failed"
      failed_when: result|changed

    - debug: msg="last task"