extractClassFieldsToCsv OneInputTransformation.fields.txt
extractClassFieldsToCsv PartitionTransformation.fields.txt
extractClassFieldsToCsv SinkTransformation.fields.txt
extractClassFieldsToCsv SourceTransformation.fields.txt
extractClassFieldsToCsv StreamTransformation.fields.txt
